[workspace]
resolver = "3"
members = ["procyon", "server"]

[workspace.dependencies]
anyhow = { version = "1.0.98", default-features = true }
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.15"
