[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
futures.workspace = true
procyon = { path = "../procyon" }
tokio.workspace = true
tokio-util.workspace = true
