name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set version
      run: sed -i 's/^version = "\(.*\)"$/version = "\1+${{ github.run_number }}"/' server/Cargo.toml
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Tag version
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag -a "build/${{ github.run_number }}" -m "Build ${{ github.run_number }}"
        git push origin "build/${{ github.run_number }}"
