name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Install libevent-dev
        run: sudo apt-get -y install libevent-dev

      - uses: actions/checkout@v4

      - name: Set version
        run: sed -i 's/^version = "\(.*\)"$/version = "\1+${{ github.run_number }}"/' server/Cargo.toml

      # https://github.com/marketplace/actions/setup-localstack
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: "latest"
          install-awslocal: "true"
          configuration: DEBUG=1
          use-pro: "false"

      - name: Setup LocalStack test data
        run: |
          awslocal secretsmanager create-secret \
            --name "dev/secrets1/abc" \
            --description "For platypus testing" \
            --secret-string "abc-test-value"

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Tag version
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a "build/${{ github.run_number }}" -m "Build ${{ github.run_number }}"
          git push origin "build/${{ github.run_number }}"
